name: 构建core镜像

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 拉取代码
      uses: actions/checkout@v2.5.0
    - name: 构建镜像并推送仓库
      run: |
        VERSION=$(cat VERSION)
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.cn-beijing.aliyuncs.com
        docker build -f core/Dockerfile -t registry.cn-beijing.aliyuncs.com/marbleqi/jms-core:${VERSION} .
        docker push registry.cn-beijing.aliyuncs.com/marbleqi/jms-core:${VERSION}
      env: 
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
