name: 制作镜像并推送到私有仓库

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 拉取代码
      uses: actions/checkout@v2.5.0
    - name: 制作镜像并推送到私有仓库
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.cn-beijing.aliyuncs.com
        VERSION=$(cat VERSION)
        TARGETARCH=$(cat TARGETARCH)
        docker build -f core/Dockerfile -t registry.cn-beijing.aliyuncs.com/marbleqi/jms-core:${VERSION} .
        docker push registry.cn-beijing.aliyuncs.com/marbleqi/jms-core:${VERSION}
        docker build --build-arg TARGETARCH="${TARGETARCH}" -f koko/Dockerfile -t registry.cn-beijing.aliyuncs.com/marbleqi/jms-koko:${VERSION} .
        docker push registry.cn-beijing.aliyuncs.com/marbleqi/jms-koko:${VERSION}
        docker build --build-arg TARGETARCH="${TARGETARCH}" -f lion/Dockerfile -t registry.cn-beijing.aliyuncs.com/marbleqi/jms-lion:${VERSION} .
        docker push registry.cn-beijing.aliyuncs.com/marbleqi/jms-lion:${VERSION}
        docker build --build-arg TARGETARCH="${TARGETARCH}" -f magnus/Dockerfile -t registry.cn-beijing.aliyuncs.com/marbleqi/jms-magnus:${VERSION} .
        docker push registry.cn-beijing.aliyuncs.com/marbleqi/jms-magnus:${VERSION}
        docker build -f web/Dockerfile -t registry.cn-beijing.aliyuncs.com/marbleqi/jms-web:${VERSION} .
        docker push registry.cn-beijing.aliyuncs.com/marbleqi/jms-web:${VERSION}
      env: 
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
